# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Doxia LinkCheck"
  homepage: https://maven.apache.org/doxia/doxia-tools/doxia-linkcheck/
  labels:
    - java
    - build-management
    - apache-maven
    - doxia
    - doxia-tools
